### ISSUE TITLE
Increase MAX_MEMORY_SIZE to 256K

### ISSUE THREAD

**Issue by drewrobson** [PaulStoffregen/teensy_loader_cli#15]
Currently, the maximum firmware size supported by Teensy Loader appears to be 128K:

```
#define MAX_MEMORY_SIZE 0x20000
```

Teensy 3.1 has 256K flash. Can we simply increase the limit to 256K?

```
#define MAX_MEMORY_SIZE 0x40000
```

**Comment by PaulStoffregen** [comment]
fixed https://github.com/PaulStoffregen/teensy_loader_cli/commit/a5b2c6fdc14c3a1ce9f614c767d9c758b0a1ce96
