### ISSUE TITLE
Soft reset not working on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by danagain** [PaulStoffregen/teensy_loader_cli#62]
I have been stumped on this issue for quite a while now. It seems that line 337 in teensy_loader_cli.c  throwing an error when opening USB device

serial_handle = open_usb_device(0x16C0, 0x0483);

Example output:

root@ubuntu:/home/ubuntu/teensy_loader_cli# ./teensy_loader_cli --mcu=TEENSY41 /home/ubuntu/firmware.hex -v -s
Teensy Loader, Command Line, Version 2.2
Read "/home/ubuntu/firmware.hex": 355478 bytes, 4.4% usage
Error opening USB device: No error
Waiting for Teensy device...
 (hint: press the reset button)

The only way I seem to be able to remotely upload my code is by pressing the button on the teensy, but this is not viable for my situation. I know that there is a workaround if using raspbian which I have used before 

SERIAL_TEENSY_DEVICE=`find /dev/serial/by-id/ -name "usb-Teensyduino*"`;
echo "-> Performing soft resset (baud = 134 hack). $SERIAL_TEENSY_DEVICE";
lsusb | grep Teensy;
stty -F $SERIAL_TEENSY_DEVICE 9600
sleep 1;
stty -F $SERIAL_TEENSY_DEVICE 134
sleep 1;
lsusb | grep Teensy;
echo "-> Should be ready to program...";
sudo ./teensy_loader_cli --mcu=imxrt1062 -v -w TEENSY4_CODE.hex

But I really need to get this command working on Ubuntu 20.04. Is there anything you can do to please help me out ? Do you know of any other workarounds I could use ?

Kind Regards,
Dan

**Comment by PaulStoffregen** [comment]
This is the wrong place to ask for help.  Use the forum for questions.
